/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get API information and version details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Project information message */
                            message?: string;
                            sources?: {
                                vanilla?: {
                                    /**
                                     * @description Minecraft vanilla version
                                     * @example 1.21.5
                                     */
                                    version?: string;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/swagger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get OpenAPI/Swagger specification for the API */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI 3.0 specification document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/vanilla/item/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all categories with items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories data object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tools_and_utilities: string[];
                            building_blocks: string[];
                            food_and_drinks: string[];
                            natural_blocks: string[];
                            op_blocks: string[];
                            functional_blocks: string[];
                            spawn_eggs: string[];
                            redstone_blocks: string[];
                            colored_blocks: string[];
                            ingredients: string[];
                            combat: string[];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Internal Server Error */
                            error?: string;
                            /** @example An error occurred while retrieving categories */
                            message?: string;
                        };
                    };
                };
                /** @description Service unavailable - categories not initialized */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Categories not initialized */
                            error?: string;
                            /** @example The categories data is not yet available. Please try again in a few moments. */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/vanilla/item/{item}/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The item identifier */
                    item: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ![Example](https://assets.zaralx.ru/api/v1/minecraft/vanilla/item/diamond_block/icon) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/webp": string;
                    };
                };
                /** @description Item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/vanilla/item/{item}/lang/{lang}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the localized name of an item in a specific language */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The item identifier */
                    item: string;
                    /** @description The language code */
                    lang: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The localized item name */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description Bad request - unknown language or item not found */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Unknown lang */
                            message?: string;
                            /** @description Available language keys (only present when language is unknown) */
                            lang_keys?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/vanilla/lang/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get language data by language identifier */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The language identifier */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Language data object containing all translations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad request - unknown language */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Unknown lang */
                            message?: string;
                            /** @description Available language keys */
                            lang_keys?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/vanilla/player/face/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get player face image by UUID or nickname */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Player UUID or Minecraft nickname */
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ![Example](https://assets.zaralx.ru/api/v1/minecraft/vanilla/player/face/_zaralX_) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                /** @description Bad request - invalid UUID or nickname */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Invalid UUID or Nickname */
                            message?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Failed to fetch skin */
                            message?: string;
                            /** @description Error message */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/vanilla/player/face/{identifier}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get full player face image (with layers) by UUID or nickname */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Player UUID or Minecraft nickname */
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ![Example](https://assets.zaralx.ru/api/v1/minecraft/vanilla/player/face/_zaralX_/full) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                /** @description Bad request - invalid UUID or nickname */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Invalid UUID or Nickname */
                            message?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Failed to fetch skin */
                            message?: string;
                            /** @description Error message */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/minecraft/vanilla/player/skin/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get player skin image by UUID or nickname */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Player UUID or Minecraft nickname */
                    identifier: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ![Example](https://assets.zaralx.ru/api/v1/minecraft/vanilla/player/skin/_zaralX_) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                /** @description Bad request - invalid UUID or nickname */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Invalid UUID or Nickname */
                            message?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Failed to fetch skin */
                            message?: string;
                            /** @description Error message */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
