/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applications/complete/{query}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["complete_application"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_application"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_application"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/get/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_application"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/search/{application_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_application"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/add_member/{group_id}/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_member_to_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/add_subowner/{group_id}/{subowner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["add_subowner_to_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/change/label": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["change_group_label"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/complete/{query}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["complete_group"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_group"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/get/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_group"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/handover/{group_id}/{new_owner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["handover_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/kick_member/{group_id}/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["kick_member_from_group"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/kick_subowner/{group_id}/{subowner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["kick_subowner_from_group"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/logs/{from}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_group_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/membered/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["membered_group"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/search/{group_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_group"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/complete/{query}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["complete_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/get/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/logs/{from}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_logs_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/search/{nickname}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationCompleteResponse: {
            applications: components["schemas"]["ApplicationProjectionResponse"][];
        };
        ApplicationCreateRequest: {
            description: string;
            name: string;
            /** Format: uuid */
            owner_id: string;
        };
        ApplicationCreateResponse: {
            application: components["schemas"]["ApplicationProjectionResponse"];
        };
        /** @default null */
        ApplicationDeleteResponse: unknown;
        ApplicationGetResponse: {
            application: components["schemas"]["ApplicationProjectionResponse"];
        };
        ApplicationProjectionResponse: {
            full: {
                description: string;
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                judgement_id?: string | null;
                label: string;
                name: string;
                /** Format: uuid */
                owner_id: string;
            };
        };
        ApplicationSearchResponse: {
            application: components["schemas"]["ApplicationProjectionResponse"];
        };
        DiscordProfileProjectionResponse: {
            discord_avatar: string;
            discord_id: string;
            discord_label: string;
            discord_nickname: string;
        };
        /** @default null */
        GroupAddMemberResponse: unknown;
        /** @default null */
        GroupAddSubownerResponse: unknown;
        GroupChangeLabelRequest: {
            /** Format: uuid */
            group_id: string;
            label: string;
        };
        /** @default null */
        GroupChangeLabelResponse: unknown;
        GroupCompleteResponse: {
            groups: components["schemas"]["GroupProjectionResponse"][];
        };
        GroupCreateRequest: {
            name: string;
            /** Format: uuid */
            owner_id: string;
        };
        GroupCreateResponse: {
            group: components["schemas"]["GroupProjectionResponse"];
        };
        /** @default null */
        GroupDeleteResponse: unknown;
        GroupGetResponse: {
            group: components["schemas"]["GroupProjectionResponse"];
        };
        /** @default null */
        GroupHandoverResponse: unknown;
        /** @default null */
        GroupKickMemberResponse: unknown;
        /** @default null */
        GroupKickSubownerResponse: unknown;
        GroupMemberedResponse: {
            groups: components["schemas"]["GroupProjectionResponse"][];
        };
        GroupProjectionResponse: {
            full: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                judgement_id?: string | null;
                label: string;
                member_ids: string[];
                name: string;
                /** Format: uuid */
                owner_id: string;
                subowner_ids: string[];
            };
        };
        GroupSearchResponse: {
            group: components["schemas"]["GroupProjectionResponse"];
        };
        LogBaseProjectionResponse: {
            chain: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            executor_id: string;
            /** Format: uuid */
            initiator_id: string;
            /** Format: uuid */
            trace_id: string;
        };
        MinecraftProfileProjectionResponse: {
            minecraft_cape: string;
            minecraft_nickname: string;
            /** Format: uuid */
            minecraft_profile_id: string;
            minecraft_skin: string;
        };
        UserCompleteResponse: {
            users: components["schemas"]["UserProjectionResponse"][];
        };
        UserEventProjectionResponse: {
            Create: {
                discord_profile: components["schemas"]["DiscordProfileProjectionResponse"];
                minecraft_profile: components["schemas"]["MinecraftProfileProjectionResponse"];
            };
        } | {
            ChangeMinecraftProfile: {
                profile: components["schemas"]["MinecraftProfileProjectionResponse"];
            };
        } | {
            ChangeDiscordProfile: {
                profile: components["schemas"]["DiscordProfileProjectionResponse"];
            };
        } | {
            Blocked: {
                /** Format: uuid */
                judgement_id?: string | null;
            };
        } | {
            Deleted: {
                payload: boolean;
            };
        };
        UserGetResponse: {
            user: components["schemas"]["UserProjectionResponse"];
        };
        UserLogProjectionResponse: {
            base: components["schemas"]["LogBaseProjectionResponse"];
            event: components["schemas"]["UserEventProjectionResponse"];
            /** Format: uuid */
            group_id: string;
            /** Format: uuid */
            id: string;
        };
        UserLogsResponse: {
            logs: components["schemas"]["UserLogProjectionResponse"][];
        };
        UserProjectionResponse: {
            full: {
                discord_id: string;
                /** Format: uuid */
                judgement_id?: string | null;
                minecraft_cape: string;
                minecraft_nickname: string;
                /** Format: uuid */
                minecraft_profile_id: string;
                minecraft_skin: string;
                /** Format: uuid */
                user_id: string;
            };
        } | {
            restricted: {
                /** Format: uuid */
                judgement_id?: string | null;
                minecraft_cape: string;
                minecraft_nickname: string;
                /** Format: uuid */
                minecraft_profile_id: string;
                minecraft_skin: string;
                /** Format: uuid */
                user_id: string;
            };
        };
        UserSearchResponse: {
            user: components["schemas"]["UserProjectionResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    complete_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationCompleteResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    create_application: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreateRequest"];
            };
        };
        responses: {
            /** @description Application retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationCreateResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    delete_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDeleteResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationGetResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    search_application: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSearchResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    add_member_to_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member added successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupAddMemberResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    add_subowner_to_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                subowner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subowner added successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupAddSubownerResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    change_group_label: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupChangeLabelRequest"];
            };
        };
        responses: {
            /** @description Group changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupChangeLabelResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    complete_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupCompleteResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    create_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreateRequest"];
            };
        };
        responses: {
            /** @description Group created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupCreateResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    delete_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupDeleteResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupGetResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    handover_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                new_owner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group handover successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupHandoverResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    kick_member_from_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member kicked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupKickMemberResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    kick_subowner_from_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
                subowner_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subowner kicked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupKickSubownerResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_group_logs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                from: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group logs getted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    membered_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMemberedResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    search_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupSearchResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    complete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCompleteResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGetResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_logs_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                from: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User logs get successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserLogsResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    search_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nickname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearchResponse"];
                };
            };
            /** @description Default kts error format */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
